### PR TITLE
Fix: Make `/Annots` indirect

### LINKED ISSUE #15: Annots attribute should contain indirect references
According to the pdf 1.7 standard (7.7.3.2, Table 30) the `Annots` attribute in a `Page` dictionary should contain indirect references, however this library directly puts the annotation dictionaries into the page dictionary.

Most (all?) pdf readers seem to deal fine with the indirect references, however when looking into what would be needed to support interactive forms in pdfs (https://github.com/typst/typst/issues/1765) I noticed that in this case annotation dictionaries need to be referenced from multiple places at once (the page on which they are placed and the form field which they represent).
This is only possible with indirect references.

Note that this change would require an backwards-incompatible API change.

### PR DESCRIPTION
**Pull request by tingerrr**
Resolves #15, and unblocks #25. This introduces a **breaking change**.

### CODE REVIEW

File: src/structure.rs [hunk 1]
```diff
@@ -1167,9 +1167,10 @@ impl<'a> Page<'a> {
         self.insert(Name(b"Trans")).start()
     }
 
-    /// Start writing the `/Annots` (annotations) array.'
-    pub fn annotations(&mut self) -> TypedArray<'_, Annotation> {
-        self.insert(Name(b"Annots")).array().typed()
+    /// Start writing the `/Annots` (annotations) array.
```
Comment (reknih) [inline src/structure.rs:1170]:
```suggestion
    /// Write the `/Annots` (annotations) array.
```

**Comment by laurmaedje** [comment]
Thanks!
